### ISSUE TITLE
Have browser list in PR template for this

### ISSUE THREAD

**Issue by cfarm** [cfpb/development#129]
- List what you have actually tested
- Ask reviewers to review specific browsers
- How useful is this checklist currently anyway? Revisit how we use this

**Comment by jimmynotjim** [comment]
- [ ] CF
- [ ] DM
- [ ] cfgov-refresh
- [ ] development
- [ ] OSS project template
- [ ]

**Comment by anselmbradford** [comment]
We have a browser list in the current PR template https://github.com/cfpb/consumerfinance.gov/blob/main/.github/PULL_REQUEST_TEMPLATE.md
