### ISSUE TITLE
Have pre-release sites deployed on build server with feature branches so they can be QAed 

### ISSUE THREAD

**Issue by cfarm** [cfpb/development#133]
- Potential BEWD allies: Marc and Will
- [x] Make it happen
- [x] Show FEWDs how to use it

**Comment by cfarm** [comment]
WE DID THIS!!! @willbarton 
🎉 🎈 🎆 🎉 🎈 🎆 🎉 🎈 🎆 🎉 🎈 🎆 🎉 🎈 🎆 🎉 🎈 🎆 🎉 🎈 🎆 🎉 🎈 🎆 🎉 🎈 🎆 🎉 🎈 🎆 🎉 🎈 🎆 🎉 🎈 🎆 🎉 🎈 🎆 🎉 🎈 🎆 🎉 🎈 🎆 🎉 🎈 🎆 🎉 🎈 🎆 🎉 🎈 🎆 🎉 🎈 🎆 🎉 🎈 🎆 🎉 🎈 🎆 🎉 🎈 🎆 🎉 🎈 🎆 🎉 🎈 🎆 🎉 🎈 🎆 🎉 🎈 🎆 🎉 🎈 🎆 🎉 🎈 🎆 🎉 🎈 🎆 🎉 🎈 🎆 🎉 🎈 🎆 🎉 🎈 🎆 🎉 🎈 🎆 🎉 🎈 🎆 🎉 🎈 🎆 🎉 🎈 🎆 🎉 🎈 🎆 🎉 🎈 🎆 🎉 🎈 🎆 🎉 🎈 🎆 🎉 🎈 🎆 🎉 🎈 🎆 🎉 🎈 🎆 🎉 🎈 🎆 🎉 🎈 🎆 🎉 🎈 🎆 🎉 🎈 🎆 🎉 🎈 🎆 🎉 🎈 🎆 🎉 🎈 🎆

**Comment by jimmynotjim** [comment]
@cfarm showed the rest of us how it works too!
