### ISSUE TITLE
Need general policy for which browsers to support in which contexts

### ISSUE THREAD

**Issue by cfarm** [cfpb/development#135]
Make it clear which browsers, functionality to test, and how. 

### draft a policy/recommendation from FEWD perspective 
For an upcoming meeting (12/5):
- [x] Cat will create a Google Doc 
- [x] Share out to get questions/suggestions from FEWDs in advance.
- [x] During meeting, we'll start live-drafting the policy together!
- [x] Go line by line through current list of support and discuss and make decisions on changes.

### once FEWDs approve draft
- [ ] present it to stakeholders (designers, product owners, Adam)
- [ ] adjust with feedback as needed
- [ ] get signoff on making this the standard

## Acceptance criteria

- Make sure you have an experience that’s as feature complete/accessible as possible for each browser in list.
- Do we want to specify CSS/HTML features too? Especially what fallbacks are needed or polyfills - with and without js
- What level of support are we committing to from now on? 
- With what methods will we test and achieve that support?(For example, we may decide to manually test some browsers until automated testing is implemented, etc).

**Comment by cfarm** [comment]
we labeled this HH meaning "double high priority" 😸

**Comment by contolini** [comment]
- How do we talk to stakeholders about the importance of browser support?
- If you feel you can’t support our baseline browsers given complex project requirements, what should you do?
- If your think your project has a unique user demographic with unusual device usage, how can you safely stray from our standard browser support guidelines?

**Comment by cfarm** [comment]
More wishlist for outcomes for this task
- Understand when we can adopt the newest browser features
- Standardize our decision-making process
- Feature-based descriptions of support such as specific DOM events or component/UI interactions

**Comment by cfarm** [comment]
@jimmynotjim and @virginiacc volunteered to draft a proposal to define an active vs passive browser support policy based on Virginia's idea

**Comment by cfarm** [comment]
@Scotchester volunteered to do the following task for this: 

Sketch potential application of active/passive support policy. It should help us answer the question, “How would we apply the policy to pages/browsers?”

**Comment by cfarm** [comment]
@Scotchester please share an update when you're back!

**Comment by Scotchester** [comment]
Here's what I developed so far. It's definitely not pretty, but if the general format works for people, we could ask a designer to help pretty it up. Feedback welcome!

![screen shot 2018-01-23 at 10 59 29](https://user-images.githubusercontent.com/1044670/35285948-9ab868f6-002c-11e8-93fd-a93c5ad529d8.png)

**Comment by cfarm** [comment]
@jimmynotjim I think the policy should be added to the Browser Support Guide (or linked, at least) https://github.com/cfpb/development/blob/cb01b571ad3d97124466261cbc31a751eabe7a9d/guides/browser-support.md

**Comment by cfarm** [comment]
Some quotes from these 2 pieces would be helpful to include in our policy when describing our approach to JavaScript fallback/progressive enhancement implementations:

https://www.gov.uk/service-manual/technology/using-progressive-enhancement
https://gds.blog.gov.uk/2013/10/21/how-many-people-are-missing-out-on-javascript-enhancement/

**Comment by jimmynotjim** [comment]
We finished this too, yay!
