### ISSUE TITLE
Get the latest versions of browsers for our Macs on a timely basis. (especially Firefox, Safari)

### ISSUE THREAD

**Issue by cfarm** [cfpb/development#138]

**Comment by anselmbradford** [comment]
How do we go about getting the latest? E.g. an updated FF by default without needing to download our own updated version?

**Comment by Scotchester** [comment]
For Firefox, given that we now have auto-updating enabled on Chrome, I think we just need to get them to agree to treat Firefox the same way and auto-update it.

Safari is a tougher nut to crack, though, because Apple is stupid and only updates Safari with OS updates.

**Comment by jimmynotjim** [comment]
For now we'll rely on SauceLabs but it'd still be nice to have these updated. Maybe we can get Adam in our corner on this.

**Comment by jimmynotjim** [comment]
@ascott1 is working on getting us the latest version of FF. Not sure on a timeline at this point but it sounds like local tests on his machine have gone well.

**Comment by cfarm** [comment]
is this still actively being worked on? if not i'll move it to the backlog 🕺

**Comment by anselmbradford** [comment]
For FF, it's changed so we can update it ourselves. For Safari, I have the latest installed. We can probably close this issue?

**Comment by Scotchester** [comment]
Yeah, seems like it's done. Not sure when it changed that Safari could be updated outside OS releases, but that's good.
