### ISSUE TITLE
Make it easy to test quickly in browsers we say we support, so that we test all the browsers we claim to support!

### ISSUE THREAD

**Issue by cfarm** [cfpb/development#144]

**Comment by jimmynotjim** [comment]
What we've done:
- Created a list of browsers to test
- Started instructions on how to install local VMs for IE browsers

What we need to do:
- Revisit our SauceLabs tunnel 
- Document how to best use SauceLabs and create a level of comfort with it
  - Share Cat's alias
  - Share tips and tricks
  - Pairing session with Cat
  - Save all this in /development for the future

**Comment by cfarm** [comment]
Assigning here and noting to self to do #103 for next meeting in 2 weeks

**Comment by cfarm** [comment]
The tasks related to this are https://github.com/cfpb/development/issues/139 (still in progress) and #162 (done) so I think we can close this particular issue
