### ISSUE TITLE
Standardize our supported browser list config format

### ISSUE THREAD

**Issue by cfarm** [cfpb/development#148]
- One single file with the config list of browsers we support
- Optionally add more granular detail (e.g. separate list for CSS/JS support etc)
- Create [development/.browserslistrc](https://github.com/cfpb/development/blob/master/.browserslistrc) file and add browsers to it.

Document it in the [browserslist](https://github.com/ai/browserslist) format. See [hmda-platform-ui](https://github.com/cfpb/hmda-platform-ui/blob/master/.browserslistrc) for an example.

**Comment by Scotchester** [comment]
Investigate https://github.com/ai/browserslist

**Comment by cfarm** [comment]
https://github.com/cfpb/hmda-platform-ui/blob/master/.browserslistrc

**Comment by cfarm** [comment]
We'd like to have this done in 2 weeks by our next meeting (11/28) so we can share and discuss before moving on to #135
