### ISSUE TITLE
Document browser usage from Google Analytics of key sites/apps

### ISSUE THREAD

**Issue by cfarm** [cfpb/development#149]
Acceptance criteria:

- Understand overall browser usage on cf.gov
- Understand which key pages have unique profiles of users, for example, if some pages have more mobile users, IE8 users, etc.

**Comment by cfarm** [comment]
Key sites: https://GHE/CFGOV/platform/wiki/Key-pages-for-QA%2C-testing%2C-analytics

**Comment by cfarm** [comment]
We'd like to have this done in 2 weeks by our next meeting (11/28) so we can share and discuss before moving on to #135

**Comment by sephcoster** [comment]
👍  Done.

**Comment by Scotchester** [comment]
Where?

**Comment by Scotchester** [comment]
Answer: Linked to from meeting agenda.

**Comment by contolini** [comment]
Reopening to remind myself to export stats concerning some unanswered questions we have.

**Comment by cfarm** [comment]
Bump: @contolini is gonna attempt to make a Google Studio dashboard with the following analytics: A list of key pages (browser breakdown for key pages, with version number)
