### ISSUE TITLE
Supported versions of Python and other dependencies in applications and libraries

### ISSUE THREAD

**Issue by willbarton** [cfpb/development#199]
As we remove Python 2.7 support from our libraries ([django-flags](https://github.com/cfpb/django-flags), [wagtail-flags](https://github.com/cfpb/wagtail-flags), [wagtail-inventory](https://github.com/cfpb/wagtail-inventory), [wagtail-sharing](https://github.com/cfpb/wagtail-sharing), [wagtail-treemodeladmin](https://github.com/cfpb/wagtail-treemodeladmin)), we've come to an interesting question that I think is worth standardizing: what versions of Python and major dependencies (i.e. Django, Wagtail) do we intend to support and test against.

There's [some discussion in this Wagtail Sharing PR](https://github.com/cfpb/wagtail-sharing/pull/29) for context, but I'd like to make a proposal based on what @chosak has suggested and what @cwdavies has done:

### For libraries

We should support and test against the version we use in production (which I think we should intend to be the latest LTS release) and then the latest release. So for Django+Wagtail, that would mean:

- The version of Django we use in production (which should be LTS)
- The latest version of Django
- The version of Wagtail we use in production (which should be LTS)
- The latest version of Wagtail

For Python support *in our libraries*, I think we should include support for the oldest version of Python that our major dependencies support. So, for example, Django 1.11 supports Python 3.5 and up. So we should do the same, because if there are other folks using our libraries, they could be using any of those versions of Python.

### For applications

I am thinking specific of https://github.com/cfpb/cfgov-refresh in this case — the things that consume our libraries and that we run in environments we control. I think I'd propose the same matrix of support for major dependencies: **current production version (LTS) + latest released version**.

- The version of Django we use in production (which should be LTS)
- The latest version of Django
- The version of Wagtail we use in production (which should be LTS)
- The latest version of Wagtail

For Python I think it's simpler: production version and the latest version, so 3.6 and 3.8. 

---

There's probably a little more art to this than science, and I know from trying to figure out which versions things like Django Flags and Wagtail Flags should support that there's quite a bit of judgement involved... but for guidelines to make it that little bit easier to decide, I think this is what I'd propose.

What do you all think?

**Comment by Scotchester** [comment]
> For Python support _in our libraries_, I think we should include support for the oldest version of Python that our major dependencies support. So, for example, Django 1.11 supports Python 3.5 and up. So we should do the same, because if there are other folks using our libraries, they could be using any of those versions of Python.

I agree with this principle.

And in general, I agree with your entire proposal. The only question I'd ask is: For cfgov-refresh or other applications, would we have any reason to want to go to 3.7 before 3.8?

**Comment by higs4281** [comment]
I agree with this plan, but when I check `pyenv install --list` the only python 3.8 version available is 3.8-dev. Do we want to test with that or hold off until a non-dev version is available?

**Comment by willbarton** [comment]
@higs4281 I think you have to update `pyenv` for new versions of Python. It uses a local list, and doesn't remotely fetch the available versions, IIRC.

**Comment by higs4281** [comment]
> @higs4281 I think you have to update `pyenv` for new versions of Python. It uses a local list, and doesn't remotely fetch the available versions, IIRC. The latest has `3.8.0` and `3.8.1`.

Right you are! `brew upgrade pyenv` updates the local list.

**Comment by willbarton** [comment]
> And in general, I agree with your entire proposal. The only question I'd ask is: For cfgov-refresh or other applications, would we have any reason to want to go to 3.7 before 3.8?

I don't think there's a reason to for applications. I think the "current in production + latest" rubric works for Python too.

**Comment by willbarton** [comment]
If this makes sense to everyone, I'll write up a doc and PR it to this repo for further review and comment.

**Comment by schbetsy** [comment]
Ready to close?

**Comment by Scotchester** [comment]
I think so. PR got merged!
