### ISSUE TITLE
Libraries we use

### ISSUE THREAD

**Issue by ascott1** [cfpb/development#46]
Let's compile a list of all of the libraries and frameworks we use across our projects. List 'em for your project below!

**Comment by cfarm** [comment]
## Owning a Home
### JS
* jQuery
* React
* Handlebars templates
* Highcharts

### CSS/JS
* Capital Framework
* Bootstrap (for tooltips, not sure what else)


@virginiacc am I missing anything? @contolini can add testing stuff

**Comment by mistergone** [comment]
## Retirement

### JS
- jQuery
- Raphael

### CSS
- Capital Framework

**Comment by mistergone** [comment]
## Paying for College

### JS
- jQuery
  - decisionStacker (custom plugin)
- Raphael

### CSS
- Capital Framework (kind of. Various aspects of CF were implemented the last time the site was rebuilt, but it was an early version. Notable exception: the "Repaying Student Debt" portion of the site uses the latest CF.

**Comment by ascott1** [comment]
## eRegs

### JS

- Backbone
- jQuery
- Underscore

#### Smaller JS libs

- [jquery-scrollstop](https://github.com/ssorallen/jquery-scrollstop) for tracking when scrolling starts/stops and updating the wayfinding subhead
- [Unveil](https://github.com/luis-almeida/unveil) for lazy loading images

### CS

- normalize.css

### shim, shivs, polyfills, feature detection, etc.

- modernizr
- html5shiv
- respond.js
- indexOf polyfill

**Comment by imuchnik** [comment]
Wiki Search
JQuery
Handlebars
Jasmine

**Comment by contolini** [comment]
## [Dash](https://github.com/cfpb/dash)

### JS
* React
* Backbone (collections and models are used as Flux stores)
* lodash
* react-router
* react-typeahead

### CSS
* Capital Framework

### Tooling
* Browserify
* Gulp

### Testing
* Jest :expressionless: 
* Jasmine
* ESLint

## [HMDA Explorer](https://github.com/cfpb/hmda-explorer)

### JS
* jQuery
* ZeroClipboard
* Highcharts
* Bootstrap tooltips
* Chosen

### CSS
* Font Awesome
* cf-icons

### Polyfills
* html5-shiv
* normalize-css
* es5-shim
* jquery-jsonp
* json3

### Tooling
* Grunt

### Testing
* Jasmine

**Comment by sephcoster** [comment]
## [Mapusaurus](https://github.com/cfpb/mapusaurus)

### JS
* jQuery
  * Typeahead
  * Easing
  * Tablesorter
  * Tooltipsy
* Underscore
* Leaflet (0.8 Dev)
  * Leaflet-hash custom implementation
  * Leaflet-MiniMap
  * Leaflet-Rrose (tooltip alignment)
  * Leaflet-UTFGrid (because we're using Leaflet 0.8dev)
* Mapbox.js (Standalone)

### CSS
* Normalize
* Capital Framework

### Tooling
* Grunt
* LESS

### Testing
* Behave / Selenium

**Comment by KimberlyMunoz** [comment]
## [cfgov-refresh](https://github.com/cfpb/cfgov-refresh)

### JS
* jQuery
  * Easing
  * History.js
* String_Score
* Slick Carousel
* Chosen

### CSS
* Normalize
* Capital Framework

### shim, shivs, polyfills, feature detection, etc.
* HTML5Shiv
* Browserify Shim
* box-sizing polyfill
* normalize legacy addon

### Testing
* Mocha with Chai and Sinon
* JSDom
* Istanbul for coverage

@anselmbradford, @jimmynotjim, @sebworks: feel free to edit to add anything I missed.

**Comment by awolfe76** [comment]
## HDMA Pilot

### JS

- Angular
- jQuery

### CSS

- Normalize
- CF

### Tooling

- Browserify
- Grunt

### Documentation

- JSDoc

### Testing

- Cucumber
- Protractor

**Comment by awolfe76** [comment]
## HDMA - Reports

### JS

- Mustache.js
- jQuery

### CSS

- Normalize
- Custom Sass

### Tooling

- Jekyll

**Comment by awolfe76** [comment]
## HDMA - Grasshopper UI

### JS

- jQuery
- Mapbox.js

### CSS

- Normalize
- Custom Sass

### Tooling

- Grunt
- Browserify

**Comment by awolfe76** [comment]
## HMDA - Technical Data Specification

### JS

- jQuery
- Handlebars

### CSS

- Custom Sass (again)

### Tooling

- Grunt
- Browserify
- jsondiffpatch

**Comment by ascott1** [comment]
We should find a home for this long-term and tally the common libraries.

**Comment by KimberlyMunoz** [comment]
18F has a great little bit on libraries and frameworks in general that we could fork as part of that. 

https://github.com/18F/frontend/blob/master/pages/recommended_dependencies.md

**Comment by KimberlyMunoz** [comment]
Writing something for this. Do we have consensus on these as our "common" libraries

## JS Libraries
- jQuery
- Handlebars and Mustache.js
- Chosen
- Mapbox.js

## JS Framework
- Backbone 
- Angular - Someone may need add more details about how both are used in the Bureau. I think there's been discussion about using Angular on future projects.

## CSS
- Normalize
- Capital Framework

## Testing
- Mocha or Jasmine

## Tooling
- Browserify
- Grunt
- Less

**Comment by ascott1** [comment]
That looks pretty accurate to me @KimberlyMunoz. Nicely done! 

One note: We only use Backbone in one production application and I'm not sure if there's interest in using it in any new apps. I don't see us moving eRegs to another JS framework any time soon, so it's probably still worth including.

In terms of Angular, so far we've only used it on internal facing projects. Though, that hasn't necessarily been an intentional choice.

**Comment by anselmbradford** [comment]
Flapjack is now using gulp instead of grunt as of https://github.com/cfpb/cfgov-refresh/pull/797

**Comment by KimberlyMunoz** [comment]
I don't think I'll add that to our "common" libraries, but feel free to edit my post above for what Flapjack is currently using. I think y'all added some new polyfills too, right?

**Comment by ascott1** [comment]
Based on today's meeting, let's codify the above and maybe create some sort of decision tree for when we want to break away from one of our recommended libraries.

That might include things like:

- Can you articulate why your chosen library is a better fit for your project?
- Do we have the in-house capabilities to support this library?
- Is the library well tested and used widely by the development community outside of CFPB?

**Comment by ascott1** [comment]
Let's document and close this issue.
