### ISSUE TITLE
Add performance guide

### ISSUE THREAD

**Issue by ascott1** [cfpb/development#86]
:rabbit: :dash:

**Comment by wpears** [comment]
Oh boy

**Comment by djdrisco** [comment]
This tool was helpful in dealing with performance issues:
https://developers.google.com/web/tools/profile-performance/evaluate-performance/timeline-tool

**Comment by anselmbradford** [comment]
Guide development is happing in https://github.cfpb.gov/CFGOV/platform/wiki/Performance
